# Generated by Django 3.1.2 on 2020-11-01 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthProj', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
